/**
 * OPNet contract addresses and ABI definitions for the faucet.
 * Update ALPHA_ADDRESS and BETA_ADDRESS after each redeployment.
 */

export const NETWORK_NAME = 'OPNet Testnet';
export const RPC_URL = 'https://testnet.opnet.org';

/** AlphaToken v4 — has mine() */
export const ALPHA_ADDRESS = 'opt1sqrfpr855j4ngqsyyejc00fvheult7s3mjug2pz9n';
/** BetaToken v4 — has mine() */
export const BETA_ADDRESS = 'opt1sqpjcuujxqtgawt6ck8qxdw6pue728rkcnghpp084';

/** Cost to mine: 0.00001 BTC = 1000 satoshis */
export const MINE_COST_SATS = BigInt(1000);
/** Tokens received per mine call */
export const MINE_REWARD_TOKENS = 100;

/**
 * OPNet ABI for mine() — the only function we call from the faucet.
 * Selector: 0x417c69bb  (generated by opnet-transform for `mine()`)
 */
// BitcoinAbiTypes.Function = 'function' (lowercase), ABIDataTypes.UINT256 = 'UINT256'
export const MINE_ABI = [
    {
        name: 'mine',
        type: 'function',
        payable: true,
        inputs: [],
        outputs: [{ name: 'amount', type: 'UINT256' }],
    },
];
