/**
 * OPNet contract addresses and ABI definitions for the faucet.
 * Update ALPHA_ADDRESS and BETA_ADDRESS after each redeployment.
 */

export const NETWORK_NAME = 'OPNet Testnet';
export const RPC_URL = 'https://testnet.opnet.org';

/** AlphaToken v2 — has mine() */
export const ALPHA_ADDRESS = 'opt1sqq0k32mjtxlhlsvwfn7awevg2h3vamaxrvhtz5th';
/** BetaToken v2 — has mine() */
export const BETA_ADDRESS = 'opt1sqrlu3rjls5eu49jkhed3z32t2ptf4jdxt5c0hnn5';

/** Cost to mine: 0.00001 BTC = 1000 satoshis */
export const MINE_COST_SATS = BigInt(1000);
/** Tokens received per mine call */
export const MINE_REWARD_TOKENS = 100;

/**
 * OPNet ABI for mine() — the only function we call from the faucet.
 * Selector: 0x417c69bb  (generated by opnet-transform for `mine()`)
 */
export const MINE_ABI = [
    {
        name: 'mine',
        type: 'Function',
        payable: true,
        onlyOwner: false,
        inputs: [],
        outputs: [{ name: 'amount', type: 'UINT256' }],
    },
] as const;
